### ISSUE TITLE
Compare MONDO

### ISSUE THREAD

**Issue by drseb** [monarch-initiative/monarch-disease-ontology#171]
I suggest to compare MEDIC and MONDO. Reviewers might bring this up anyway.

http://ctdbase.org/downloads/#alldiseases

**Comment by pnrobinson** [comment]
?

Why? They do not have gene-disease association.

Peter Robinson

Professor of Computational Biology

The Jackson Laboratory for Genomic Medicine

10 Discovery Drive

Farmington, CT 06032

860.837.2095 t | 860.990.3130 m

peter.robinson@jax.org<mailto:peter.robinson@jax.org>

www.jax.org

Robinson lab: https://robinsongroup.github.io/

The Jackson Laboratory: Leading the search for tomorrow's cures

________________________________

**Comment by drseb** [comment]
MONDO doesn't either. Both resources are dealing with the integration of diseases from different sources. Not sure why you are bringing up gene association!?

**Comment by mellybelly** [comment]
I agree that our documentation and the eventual manuscript should compare the methods used to generate MEDIC vs. MONDO. MONDO would likely be a preferred and more maintainable resource than MEDIC for those organizations that are using it. 

MEDIC was essentially a prior effort to integrate MeSH and OMIM to provide fuller coverage over disease classification. At the time, DO didn't have much traction/content and did not have the leaf nodes. Now DO is adding OMIM, MedGen exists and does as well, and we too have integrated OMIM and MeSH into MONDO.

So I do think that this will require some discussion of the different approach. The CTD paper explains how they built MEDIC: [https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3308155/]

Essentially it is this part of pulling OMIM into MeSH that we would compare with:

1. An OMIM primary term is either merged directly to the most appropriate MeSH term or else is made a leaf (child) of one or more MeSH terms. Example: ‘LUNG CANCER’ (OMIM:211980) is merged to ‘Lung Neoplasms’ (MESH:D008175), while ‘MYELOPROLIFERATIVE DISORDER, CHRONIC, WITH EOSINOPHILIA’ (OMIM:131440) is made a leaf of two terms: ‘Myeloproliferative Disorders’ (MESH:D009196) and ‘Eosinophilia’ (MESH:D004802). An individual OMIM term cannot be both merged to and made a leaf of MeSH terms. An OMIM term cannot be made the leaf of another OMIM term.

2. If an OMIM disease term uses the word ‘susceptibility’ in its name, then that term is merged to the MeSH disease term that is concordant with the core name of the OMIM term. Example: ‘ASTHMA, SUSCEPTIBILITY TO’ (OMIM:600807) is merged to ‘Asthma’ (MESH:D001249). However, if the OMIM ‘susceptibility’ term is a complex of different diseases that do not match a single MeSH term, the OMIM term should be added as a leaf beneath all the appropriate MeSH terms. Example: ‘BREAST-OVARIAN CANCER, FAMILIAL, SUSCEPTIBILITY TO, 2’ (OMIM:612555) is added as a leaf node beneath both ‘Breast Neoplasms’ (MESH:D01943) and ‘Ovarian Neoplasms’ (MESH:D010051).

3. If an OMIM primary term uses a phrase describing heritability (e.g. ‘hereditary’, ‘autosomal’, ‘X-linked’, etc.), then the term is added as a leaf beneath the most appropriate MeSH term(s). Example: ‘DEAFNESS, AUTOSOMAL DOMINANT 12’ (OMIM:601543) is added beneath ‘Deafness’ (MESH:D003638).

4. If an OMIM primary term uses a numeral, then it is merged to the concordant MeSH term. Example: ‘SCHIZOPHRENIA 12’ (OMIM:608543) is merged to ‘Schizophrenia’ (MESH:D012559).

5. If an OMIM primary term uses the word ‘type’, then the term is added as a leaf beneath the most appropriate MeSH term(s). Example: ‘SYNDACTYLY, TYPE 1’ (OMIM:185900) is added beneath ‘Syndactyly’ (MESH:D013576).

6. For OMIM primary terms that describe syndromes, the biocurator first checks to see if that same syndrome exists in MeSH, and if it does, then the OMIM term is merged to the MeSH term. Example: ‘CHROMOSOME 5q DELETION SYNDROME’ (OMIM:153550) is merged to ‘5q- syndrome’ (MESH:C535323). If the OMIM syndrome is not in MeSH, then the OMIM term will become a leaf beneath one or more MeSH terms. Example: ‘ALOPECIA-MENTAL RETARDATION SYNDROME 2’ (OMIM:610422) is a leaf to both ‘Alopecia’ (MESH:D000505) and Intellectual Disability’ (MESH:D008607).

 Some of these rules we would not adhere to, such as no. 2, while others are similar to the MONDO pipeline, such as no.5 (more or less).

**Comment by cmungall** [comment]
medic is one of the inputs. See the medic directory in this repo.

**Comment by cmungall** [comment]
Just to compare with the first example above, this is how kboom resolved the lung cancer xrefs. This was pretty straightforward, as the most heavily weighted choices turned out to be correct:

![img-mesh_d008175](https://cloud.githubusercontent.com/assets/50745/22809533/11c4f272-eee8-11e6-9e8e-ebe6a3b1fb62.png)

This is what lung cancer and neighbors look like:

![lung-cancer](https://cloud.githubusercontent.com/assets/50745/22809494/dbc4a49c-eee7-11e6-8b26-de1dd581ae08.png)

(brown=omim, blue=doid, grey=ncit or mesh)

**Comment by drseb** [comment]
Ok. Didn't see it. Just came across MEDIC for a review on a paper. I close this
