### ISSUE TITLE
1. Ligneous conjunctivitis SubClassOf Hypoplasminogenemia

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology#179]
Both of the orphanet terms ORPHA:722 Hypoplasminogenemia and ORPHA:97231 Ligneous conjunctivitis cross reference the OMIM term: http://omim.org/entry/217090

OMIM has combined PLASMINOGEN DEFICIENCY, TYPE I and LIGNEOUS CONJUNCTIVITIS, INCLUDED into one term. According to OMIM "Ligneous conjunctivitis is usually the initial and most common manifestation of type I congenital plasminogen deficiency." I think if the equivalency grouping is correct, then maybe ORPHA:97231 Ligneous conjunctivitis should be a synonym of ORPHA:722 Hypoplasminogenemia

![image](https://cloud.githubusercontent.com/assets/6722114/22909333/5719f87c-f208-11e6-9208-92768282be85.png)

**Comment by cmungall** [comment]
I think merging the orphanets is one valid solution (we would have to suggest this to them)

There is an argument to keep the conjunctival form as a subclass, as kboom has done. This is consistent with the reading here:

http://www.orpha.net/consor/cgi-bin/OC_Exp.php?Expert=97231
http://www.orpha.net/consor/cgi-bin/OC_Exp.php?Expert=722

But it poses the question of why not also make classes for the other site-specific forms? And in general, if a disease has variable manifestation, do we always make subclasses? This is a much deeper question, cc @mellybelly @pnrobinson 

btw, the two orphanets above are not logically connected:

![image](https://cloud.githubusercontent.com/assets/50745/22911056/b9c586c6-f212-11e6-8af9-013002ccda45.png)

**Comment by nicolevasilevsky** [comment]
Ok, what are next steps?
- [ ] suggest to Orphanet to merge the terms?
- [ ] leave it as a subclass in Mondo for now?

**Comment by pnrobinson** [comment]
I would say that this ""Ligneous conjunctivitis is usually the initial and most common manifestation of type I congenital plasminogen deficiency."" implies that the two are not the same thing. The decision as to whether to call ligneuous conjunctivitis (http://eyewiki.aao.org/Ligneous_Conjunctivitis) a phenotype feature or a disease depends on your point of view. It is not a subclass of Hypoplasminogenemia unless all patients with the latter have the former which is not the case afaik. Probably it is most simple to model thjem as separate disease not connected by a direct is_a?

**Comment by nicolevasilevsky** [comment]
Thanks @pnrobinson! 

@cmungall 
If I wanted to remove the subclass assertion, I would go to the file 'set-1-ptable.tsv' and find that row (which is pasted below) and I would change the **0.6744186046511628** to **0.0** - is that right?

(I won't make any changes before confirming this, is in fact, the change we want to make.)

OMIM:217090	Orphanet:97231	0.10077519379844961	0.6744186046511628	0.20155038759689922	0.023255813953488372

**Comment by cmungall** [comment]
you'd edit the curated-ptable.tsv file. set-1-ptable.tsv is autogenerated. Curated one overrides.

Remember if you zero out SubClassOf, that actually increases prob of SuperClass, Equiv

Use SiblingOf with p=1

**Comment by cmungall** [comment]
Note this is one we want to come back to for d2p annotations. We should record the association as phenotypic frequency?

**Comment by nicolevasilevsky** [comment]
I am remembering now how to do this, thanks @cmungall! :)

I just committed that change in the curated-ptable, let me know if I didn't do that correctly.

**Comment by nicolevasilevsky** [comment]
can this be closed?
