### ISSUE TITLE
2. Shprintzen-Goldberg syndrome SubClassOf Goldberg-Shprintzen megacolon syndrome

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology#180]
I think these two diseases are similar in name but not in the characteristics, so I don't think Shprintzen-Goldberg syndrome should be a SubClassOf Goldberg-Shprintzen megacolon syndrome.

I'm not quite sure what KBoom thought this subclass relationship should exist though, the only thing I can see is the labels are similar.

![image](https://cloud.githubusercontent.com/assets/6722114/22911035/a0cc2684-f212-11e6-8459-669a10e98b1c.png)

See [report](https://github.com/monarch-initiative/monarch-disease-ontology/blob/master/src/reports/new-subclass/orphanet.md#oculoauriculovertebral-spectrum-with-radial-defects---goldenhar-syndrome)

**Comment by cmungall** [comment]
Orphanet provided xref (category=EXACT)

**Comment by nicolevasilevsky** [comment]
@cmungall I'm noto sure what you mean, provided an exact xref to what?

**Comment by pnrobinson** [comment]
Shprintzen-Goldberg syndrome and Goldberg-Shprintzen are separate and should not be sibs or parent-child.

**Comment by cmungall** [comment]
we use SIblingOf to denote `NOT(Sub OR Super OR Equiv)`. Not a good nomenclature distinction, but this is never exposed, it's just used in the calculation. What's a better term? SeparateFrom may be too strong, as it could be taken to imply DisjoitntFrom, which is not always the case for ` NOT(Sub OR Super OR Equiv)`

**Comment by nicolevasilevsky** [comment]
Trying to revitalize this conversation - is there a term we can use in the curated ptable file to denote these are unrelated classes?

**Comment by cmungall** [comment]
If you think they should be separate, make a SiblingOf link in the curated file
