### ISSUE TITLE
5. Subcortical band heterotopia SubClassOf Lissencephaly due to LIS1 mutation

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology#183]
I think this relationship may be correct, there are not any details about each disease in the orphanet records, but orphanet cross ref's Subcortical band heterotopia to three OMIM records, one of which is the same record as is cross ref'd for Lissencephaly due to LIS1 mutation. So I think that means Subcortical band heterotopia  has all the features of Lissencephaly due to LIS1 mutation plus some additional features (and looks like two more additional genes are involved.)

![image](https://cloud.githubusercontent.com/assets/6722114/22911665/cabec4ee-f215-11e6-8717-6157c79b09cf.png)

see [report](https://github.com/monarch-initiative/monarch-disease-ontology/blob/master/src/reports/new-subclass/orphanet.md#subcortical-band-heterotopia---lissencephaly-due-to-lis1-mutation)

**Comment by cmungall** [comment]
duplicate #178
