### ISSUE TITLE
6. Transgrediens et progrediens palmoplantar keratoderma SubClassOf Erythrokeratodermia variabilis

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology#184]
These two orphanet classes lack descriptions but are both cross-ref'ing the same [OMIM class](http://omim.org/entry/133200).

![image](https://cloud.githubusercontent.com/assets/6722114/22912536/d1bbbfd6-f21a-11e6-9adc-a81fffdb8323.png)

See [report](https://github.com/monarch-initiative/monarch-disease-ontology/blob/master/src/reports/new-subclass/orphanet.md#transgrediens-et-progrediens-palmoplantar-keratoderma---erythrokeratodermia-variabilis)

**Comment by cmungall** [comment]
You can read more here: http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=308166


ordo hierarchy:

![image](https://cloud.githubusercontent.com/assets/50745/22914966/ce9505e8-f228-11e6-82cb-7e6536fee4bf.png)

**Comment by nicolevasilevsky** [comment]
Thanks Chris! I think these are sibling classes. In the OMIM description, they describe keratosis palmoplantaris transgrediens et progrediens as a separate (but co-occuring) disease for one family.

"Greither disease, also known as keratosis palmoplantaris transgrediens et progrediens, is characterized by nonbullous desquamation of erythematous palms and soles, with hyperhidrosis (Greither, 1952). Wollina et al. (1989) reported a 5-generation family in which 4 individuals, including a mother, son, the mother's brother, and his daughter, exhibited simultaneous occurrence of both erythrokeratodermia variabilis and diffuse palmoplantar hyperkeratosis of the keratosis palmoplantaris transgrediens et progrediens type. The skin lesions developed within the first month of life in all cases. Palmoplantar hyperkeratosis was a consistent feature in 10 other affected family members."

**Comment by sbello** [comment]
Hi Nicole,
OMIM has a policy of listing 'included' titles for disease which are NOT the same as the main disease of the record but are mentioned in the record and for which OMIM does not have sufficient information to warrant creating a separate record. I have noticed that Orphanet will use the OMIM ID of the record for both the main disease and any included disease(s). This creates the confusing case you have here. I don't know if anyone has spoken with them about what OMIM is doing with the 'included' titles.

**Comment by nicolevasilevsky** [comment]
Thanks Sue, good to know!

**Comment by nicolevasilevsky** [comment]
@cmungall If you agree, I can note these as being sibling classes in the curated-ptable file

**Comment by cmungall** [comment]
@nicolevasilevsky +1
