### ISSUE TITLE
10. PEHO-like syndrome -> PEHO syndrome

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology#188]
According to the x-ref'd [OMIM record](http://omim.org/entry/260565), they say the relationship between PEHO-like syndrome and PEHO syndrome is unclear though and in another description, they said it they are distinct autosomal recessive conditions (and it looks like different genes are involved, according to Orphanet).

So should these be siblings?

![image](https://cloud.githubusercontent.com/assets/6722114/23034851/0e8d8b2e-f432-11e6-923b-baef09370ab1.png)

see [report](https://github.com/monarch-initiative/monarch-disease-ontology/blob/master/src/reports/new-subclass/orphanet.md#peho-like-syndrome---peho-syndrome)

**Comment by cmungall** [comment]
It sounds like they should be siblings. Can you make it so?

A deeper question moving forward is: do we create our own groupings (e.g. "PEHO 'spectrum'" - is there an existing terminology)? Do we do this manually or automatically? Note that we can already migrate to phenotypically similar siblings in monarch, but do we want to materialize these?

**Comment by nicolevasilevsky** [comment]
I created a separate ticket for your question @cmungall  (see #190) and will close this ticket.
