### ISSUE TITLE
Protege load error

### ISSUE THREAD

**Issue by janelomax** [monarch-initiative/monarch-disease-ontology#194]
Hi - when I try and load:

https://github.com/monarch-initiative/monarch-disease-ontology/blob/master/src/mondo/mondo.owl

into Protege 5 I get an error:

org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParserException: [line=8:column=17] Expecting rdf:RDF element.

**Comment by cmungall** [comment]
You can use the raw link
https://raw.githubusercontent.com/monarch-initiative/monarch-disease-ontology/master/src/mondo/mondo.owl

We have a weird interim PURL:

http://purl.obolibrary.org/obo/upheno/doid/mondo.owl (which just 
redirects to the above)

We should have this in 2 weeks, pending OBO approval:

http://purl.obolibrary.org/obo/mondo.owl

**Comment by janelomax** [comment]
Ah yes, that works. Thanks Chris!
