### ISSUE TITLE
Dual disease/phenotype classes when merging with upheno

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-disease-ontology#197]
When merging with upheno we get 52 disease classes that are also subclasses of UPHENO:0001001.  The list of classes can be found here: https://scigraph-ontology-dev.monarchinitiative.org/scigraph/cypher/execute.json?cypherQuery=MATCH+%28phenotype%3APhenotype%29+WHERE+%28phenotype%3Adisease%29+RETURN+DISTINCT%28phenotype%29&limit=100

**Comment by cmungall** [comment]
mondo doesn't assert anything to be a phenotype or a subclass of UPHENO:0001001, so the axioms must come from somewhere else.

Let's take one and try and unwind from there:
https://scigraph-ontology-dev.monarchinitiative.org/scigraph/graph/neighbors/OMIM:135290?depth=1&blankNodes=false&direction=BOTH&entail=false&project=%2A

unfortunately it's difficult to debug post clique merge

**Comment by cmungall** [comment]
Try this, superclasses to root:

https://scigraph-ontology-dev.monarchinitiative.org/scigraph/graph/neighbors/OMIM:135290?depth=20&blankNodes=false&relationshipType=subClassOf&direction=OUTGOING&entail=false&project=%2A

a likely culprit:

```
   "sub": "OBO:NCIT_C4089",
   "obj": "HP:0005266",
   "pred": "subClassOf",
```

**Comment by cmungall** [comment]
```
  {
   "sub": "OBO:NCIT_C4089",
   "obj": "HP:0005266",
   "pred": "subClassOf",
   "meta": {
    "isDefinedBy": [
     "http://purl.obolibrary.org/obo/upheno/monarch.owl"
    ],
    "lbl": [
     "subClassOf"
    ]
   }
  },
```

unfortunately we merge the TBox into one graph before loading into Neo4j, making it harder to pinpoint the exact source.

But it should be easy to tell in Protege

**Comment by cmungall** [comment]
Found it: https://github.com/obophenotype/human-phenotype-ontology/issues/1430

**Comment by cmungall** [comment]
what are the consequences of this dual inheritance ('punning', but not strictly in the OWL sense)?

We should make code as resilient as possible. Where this is not possible we need explicit tests for every release
