### ISSUE TITLE
15. Nodular lymphocyte predominant Hodgkin lymphoma -> Classic Hodgkin lymphoma

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology#203]
Based on the image, I don't see a subclass assertion between ORPHA:86893 Nodular lymphocyte predominant Hodgkin lymphoma and ORPHA:391 Classic Hodgkin lymphoma. Is this correct that kboom is trying to suggestion a subclass assertion between these two terms?

See [report](https://github.com/monarch-initiative/monarch-disease-ontology/blob/master/src/reports/new-subclass/orphanet.md#nodular-lymphocyte-predominant-hodgkin-lymphoma---classic-hodgkin-lymphoma)
![image](https://cloud.githubusercontent.com/assets/6722114/24159457/5514542a-0e1c-11e7-94b7-5d77473d8995.png)

**Comment by cmungall** [comment]
It's snipped out in your diagram, see here:

![image](https://cloud.githubusercontent.com/assets/50745/24889863/706ac460-1e21-11e7-9a59-2d5601336f70.png)


But this is the exact same problem as #204
