### ISSUE TITLE
26. Congenital multicore myopathy with external ophthalmoplegia -> Central core disease

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology#214]
This has the same issue as I see in #213.
Is the issue actually related to multiminicore myopathy being a subclass of central core disease? #210?

![image](https://cloud.githubusercontent.com/assets/6722114/24179358/ebc14fbe-0e6b-11e7-8112-81eec0b239a9.png)

**Comment by cmungall** [comment]
Let's close this one as it's a dupe
