### ISSUE TITLE
29. Pseudohypoparathyroidism type 1C -> Pseudohypoaldosteronism

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology#218]
Similar to #217, I think this suggested subclass is incorrect.

![image](https://cloud.githubusercontent.com/assets/6722114/24213910/36ae9b32-0ef1-11e7-992a-304e7198ae2b.png)

**Comment by cmungall** [comment]
let's collect these by superclass - but this into #217
