### ISSUE TITLE
34	Hb Bart's hydrops fetalis -> Hydrops fetalis

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology#223]
This is another confusing one because the arrows in the image are showing Hb Bart's hydrops fetalis as a subclass of Non-immune hydrops fetalis, not a direct subclass of Hydrops fetalis. 

@cmungall  can you help clarify?

![image](https://cloud.githubusercontent.com/assets/6722114/24215315/9bfd3d00-0ef5-11e7-82e9-cae0f95a01fb.png)

**Comment by cmungall** [comment]
Looks like it's reporting the indirect inference, but doesn't really matter, this is worth investigating.

There is no connection between HbBartHF and either NonImmuneHG or HF. Based on labels we'd expect some connection, though of course we always go by definitions not labels.

Orphanet calls the NIHF to OMIM link an 'E', and HbBHF to OMIM link a 'NTBT'. Do we believe this? If so it would entail a connection between HbBHF to NIHF in Orphanet

**Comment by cmungall** [comment]
Let's take discussion to #224
