### ISSUE TITLE
38	Sialidosis type 1 -> Sialidosis type 2

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology#227]
I think these should be siblings. Type 2 is an early onset form, so it doesn't make sense to me that type 1 would be a child.

![image](https://cloud.githubusercontent.com/assets/6722114/24224415/48db6480-0f18-11e7-8a8f-feff2edfa99b.png)

**Comment by cmungall** [comment]
I think you're right. Can you identify the underlying bad call that lead to this inference?

**Comment by drseb** [comment]
Are they still in separate branches in orphanet? http://onlinelibrary.wiley.com/doi/10.1002/humu.22112/full
Figure 2 bottom-right

**Comment by nicolevasilevsky** [comment]
The two orphanet terms are mapped to the same [OMIM record](https://omim.org/entry/256550), which includes both terms

**Comment by cmungall** [comment]
@nicolevasilevsky - correct, and if you look at Orphanet, the mappings are E (type 2) and NTBT (type 1). If we follow this, then type1 is a subclass of type2, which doesn't make sense.

In fact in the most recent run a few weeks ago, this is no longer a possible inference, due to what looks like a incorrect call between a generic-sounding DO Glycoproteinosis and a gene-specific form:

![img-doid_0080071](https://cloud.githubusercontent.com/assets/50745/24262934/de2d5552-0fb8-11e7-8207-799f9b2b9dbf.png)

Results from this:

```
[Term]
id: DOID:3343
name: glycoproteinosis
namespace: disease_ontology
def: "A lysosomal storage disease that is characterized by a deficiency of the enzyme alpha-N -acetyl neuraminidase (sialidase)." [url:http://en.wikipedia.org/wiki/Sialidosis, url:https://en.wikipedia.org/wiki/Glycoproteinosis, url:https://www.rarediseases.org/rare-disease-information/rare-diseases/byID/302/viewAbstract]
comment: OMIM mapping submitted by NeuroDevNet. [LS].
subset: DO_FlyBase_slim  ! DO_FlyBase_slim
synonym: "Mucolipidosis type I" EXACT []
synonym: "sialidosis" EXACT []
xref: ICD10:E77.1
xref: MESH:D009081
xref: NCIT:C61267
xref: OMIM:256550
xref: SCTID:70528007
xref: UMLS:C0026697
is_a: DOID:3211  ! lysosomal storage disease
```

I'll post on the DO tracker

**Comment by cmungall** [comment]
@drseb - NSWYM by separate branches. The two types are grouped by a generic form.

Thanks for  the link to the paper with the clustering, we should find a way to include this

**Comment by cmungall** [comment]
See: https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/276

**Comment by nicolevasilevsky** [comment]
So I should add to the Curated-ptable file:
1.0 Orphanet_812 Sialidosis type 1 SiblingOf Orphanet_87876 Sialidosis type 2

yes?

**Comment by cmungall** [comment]
Yes, if we are sure that the relationship is neither equivalence nor sub/super, adding a SiblingOf is the correct thing to do. We should also consider doing this for all type Ns en masse.

In this particular case, the type 1 and type 2 is no longer a problem (but it never hurts to asserted validated axioms).

**Comment by nicolevasilevsky** [comment]
forgot to link to this ticket in the commit message, but I added 1.0 Orphanet_812 Sialidosis type 1 SiblingOf Orphanet_87876 Sialidosis type 2
to the Curated-ptable file

**Comment by nicolevasilevsky** [comment]
I think this can be closed?
