### ISSUE TITLE
Missing Orphanet:457246 Clear cell sarcoma of kidney

### ISSUE THREAD

**Issue by mwilliamson-healx** [monarch-initiative/monarch-disease-ontology#254]
The Orphanet term "Clear cell sarcoma of kidney" (orpha number 457246) is missing from the Monarch Disease Ontology. I don't suppose someone could provide an explanation of why that term is missing? My impression was that all Orphanet terms would end up in the ontology.

**Comment by drseb** [comment]
This is now in mondo.obo. I hope it is ok if I close
