### ISSUE TITLE
generate a spreadsheet from MonDO to compare NCIt classes to other vocabularies

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology#255]
need a spreadsheet for manual review for this deliverable:

T2.1: Neoplasm Subset Assessment 
Manual analysis of the neoplasm subset of DO (Disease Ontology) and NCI’s MedGen (and others to be determined depending on resources), looking for discrepancies with NCIt.

**Comment by cmungall** [comment]
http://bit.ly/ncit-kboom-drive

**Comment by cmungall** [comment]
Example:

![image](https://user-images.githubusercontent.com/50745/29052642-3a8a1166-7ba0-11e7-98b3-3a393e11bcba.png)

**Comment by nicolevasilevsky** [comment]
I think we can close this.
