### ISSUE TITLE
Review NCIT_C2977 Phyllodes Tumor mapping

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology#262]
NCIT_C2977 | Phyllodes Tumor | SuperClassOf | Orphanet_180261 | Phyllode tumor
-- | -- | -- | -- | --

![image](https://user-images.githubusercontent.com/6722114/29056483-25e371e0-7bb8-11e7-8d27-5b4c3b1843fd.png)

**Comment by nicolevasilevsky** [comment]
orphanet and NCIt both xref the same UMLS class (C0010701).
I think maybe Orpahnet_180261 Phyllode tumor and MESH_D003557 Phyllodes Tumor should be equiv to NCIT_C2977 Phyllodes Tumor?

**Comment by cmungall** [comment]
Yes, you're right.

I'm curious as to why kboom chose the configuration it did. Note all the improbably (p=0.17) links it selected. There are a few potential confounders here:

## DO doesn't have a generic breast phyllodes neoplasm

![image](https://user-images.githubusercontent.com/50745/29087979-9690199c-7c2c-11e7-9755-d86e0ba32a43.png)

DO chooses to xref benign form to the malignancy-generic: http://www.orpha.net/consor/cgi-bin/OC_Exp.php?Expert=180261 

## DO breast malignant phyllodes tumor

in DO this is

```
id: DOID:3016
name: breast malignant phyllodes tumor
namespace: disease_ontology
alt_id: DOID:1632
alt_id: DOID:3018
synonym: "Phyllodes breast neoplasm" EXACT [NCI2004_11_17:C7575]
synonym: "Phyllodes tumor, malignant (morphologic abnormality)" EXACT [SNOMEDCT_2005_07_31:87913009]
synonym: "malignant Mammary Phyllodes tumor" EXACT [NCI2004_11_17:C4504]
synonym: "malignant Phyllodes neoplasm" EXACT [NCI2004_11_17:C4275]
synonym: "malignant cystosarcoma phyllodes" EXACT []
synonym: "malignant cystosarcoma phyllodes (morphologic abnormality)" EXACT [SNOMEDCT_2005_07_31:189826001]
synonym: "malignant phyllodes tumor (morphologic abnormality)" EXACT [SNOMEDCT_2005_07_31:134331008]
synonym: "malignant phyllodes tumor of breast (disorder)" EXACT [SNOMEDCT_2005_07_31:254844000]
synonym: "phyllodes breast tumor" EXACT []
xref: MESH:D003557
xref: NCI:C4275
xref: NCI:C4504
xref: NCI:C7575
xref: SNOMEDCT_US_2016_03_01:134331008
xref: SNOMEDCT_US_2016_03_01:189826001
xref: SNOMEDCT_US_2016_03_01:254844000
xref: SNOMEDCT_US_2016_03_01:712989008
xref: SNOMEDCT_US_2016_03_01:87913009
xref: UMLS_CUI:C0238031
xref: UMLS_CUI:C0346154
xref: UMLS_CUI:C0600066
is_a: DOID:1612  ! breast cancer
```

it's xreffed and synonymized to what NCIT would consider 3 distinct classes. Really it only needs to xref C4504 which is presumably the equivalent one.

I'm still a bit perplexed about why such a substandard config was chosen. I suspect there is something subtle going on we can't see in the image, to do with the disjointness between malignant and benign, and conflation of these in DO

**Comment by cmungall** [comment]
I'll make the PR

**Comment by nicolevasilevsky** [comment]
thanks!

**Comment by cmungall** [comment]
Aha!!!

found the culprit:

```
  is_a Orphanet:96344 ! Rare gynecologic or obstetric disease
   is_a Orphanet:98063 ! Rare gynecological tumor
    is_a Orphanet:180250 ! Rare breast tumor
     is_a Orphanet:180253 ! Rare benign breast tumor
      is_a Orphanet:180261 ! Phyllode tumor *** 
```

So ORDO is inducing Phyllode tumor to be benign

This is inconsistent with ORDO defs:

Orphanet:180261 ! Phyllode tumor ***  [DEF: "Phyllode tumor is a rare fibroepithelial neoplasm accounting for less than 1% of all mammary tumors, usually presenting in adult females (most frequently between the ages of 35-55 years), ranging from benign to malignant and often presenting with well circumscribed mobile masses that grow rapidly and sometimes with additional non-specific symptoms such as dilated skin veins, nipple retraction, skin ulcers, palpable axillary lymphadenopathy or blue discoloration of the skin."]

We have to go with the logical axioms for now and treat Orphanet:180261 as equivalent to benign, despite the confusing label and definition.

cc @annieolry

**Comment by cmungall** [comment]
Oh - and the other thing to note is that in orphanet 'Phyllode tumor' is breast

In NCIT, 'phyllode' can be breast or prostate.

So the Orphanet label is __doubly__ confusing here

 1. It sounds malignancy-generic, but the graph says benign
 2. It sounds location-generic, but the graph says breast

**Comment by cmungall** [comment]
With my PR, this is what we end up with:

![image](https://user-images.githubusercontent.com/50745/29095496-cddaa354-7c45-11e7-888c-432067207dd8.png)
