### ISSUE TITLE
NCIT_C4275	Malignant Phyllodes Tumor

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology#280]
NCIT_C4275 | Malignant Phyllodes Tumor | SubClassOf | DOID_3016 | breast malignant phyllodes tumor | 0.1774747908
-- | -- | -- | -- | -- | --

![image](https://user-images.githubusercontent.com/6722114/29057967-a9accd78-7bc2-11e7-88be-e6cb9cf32308.png)

**Comment by nicolevasilevsky** [comment]
DO has a syn that xrefs NCIT_C4275

![image](https://user-images.githubusercontent.com/6722114/29092228-78727a0a-7c3a-11e7-98bd-bd75fb748eae.png)

**Comment by cmungall** [comment]
#262
