### ISSUE TITLE
NCIT_C27474 | Superficial Bladder Carcinoma

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology#366]
According to #316, carcinoma != cancer, I believe, so I think this may be incorrect.

NCIT_C27474 | Superficial Bladder Carcinoma | EquivalentTo | DOID_7371 | superficial urinary bladder cancer | 0.7905298989
-- | -- | -- | -- | -- | --

![image](https://user-images.githubusercontent.com/6722114/29233238-c4fbe35e-7ea4-11e7-86d5-101e9a5013b6.png)

**Comment by cmungall** [comment]
I'd mark it as correct, carcinoma = cancer and arises-from some epithelial cell.

Although the bladder consists of both epithelium and connective tissue, I believe the 'superficial' here refers to the superficial ureothelium which is epithelial.

Based on both the definition and the superclass in DO, it's a carcinoma:

```
[Term]
id: DOID:7371
name: superficial urinary bladder cancer
namespace: disease_ontology
def: "A carcinoma of bladder that originates in the epithelial cells (the internal lining) of the bladder wall and is limited to this area." [url:http://www.malecare.com/new_page_91.htm]
synonym: "Superficial urinary bladder carcinoma" EXACT [NCI2004_11_17:C27474]
xref: NCI:C27474
xref: SNOMEDCT_US_2016_03_01:425231005
xref: UMLS_CUI:C1336527
is_a: DOID:4007  ! bladder carcinoma
```

I think it clearer if DO was to make the primary label ..carcinoma, but what they have is not internally inconsistent (note I can't speak to how cancer clinicians use this term)

Note the NCIT def is:

"A term used by urologists to describe an infiltrating carcinoma of the bladder that has not invaded into the muscularis propria of the bladder wall regardless of histologic type or grade."

**Comment by nicolevasilevsky** [comment]
Sounds good, I think we can close this ticket then.
