### ISSUE TITLE
NCIT_C39908	Seminal Vesicle Neoplasm

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology#367]
NCIT seems to use neoplasm and tumor as synonyms sometimes, but not always. They do not have a synonym for seminal vesicle tumor in this case.

NCIT_C39908 | Seminal Vesicle Neoplasm | EquivalentTo | DOID_3855 | seminal vesicle tumor | 0.7905298989
-- | -- | -- | -- | -- | --

![image](https://user-images.githubusercontent.com/6722114/29233305-190d07ac-7ea5-11e7-8ab0-01ea403cf888.png)

**Comment by cmungall** [comment]
I think in cases like this mark as ok in spreadsheet no need for a ticket, especially if there is no complex interdependent graph
