### ISSUE TITLE
carbohydrate metabolic disorder

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology#370]
Latest kboom run failed, could not resolve:

![image](https://user-images.githubusercontent.com/50745/29252103-f2ac6428-8015-11e7-8f6f-f3148ebdb037.png)

The DO classes represent acquired and inherited forms and should not be equivalent

**Comment by cmungall** [comment]
See https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/371

**Comment by pnrobinson** [comment]
I wonder if the Orphanet term isnt implicitly referring just to inborn errors or carb metab.? There are of course lots of other diseases -- type 2 diabetes might be a good example. Perhaps one of the two DO terms?

**Comment by cmungall** [comment]
Yes, looking at the hierarchy I think this is true
