### ISSUE TITLE
NCIT_C5532 | Benign Prostate Phyllodes Tumor

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology#383]
NCIT_C5532 | Benign Prostate Phyllodes Tumor | SubClassOf | DOID_2885 | benign prostate phyllodes tumor | 0.2645762349
-- | -- | -- | -- | -- | --

 
![image](https://user-images.githubusercontent.com/6722114/29330627-a70096da-81ae-11e7-84c9-463bcfd3556e.png)

**Comment by cmungall** [comment]
#262
