### ISSUE TITLE
Orpha vs Orphanet

### ISSUE THREAD

**Issue by drseb** [monarch-initiative/monarch-disease-ontology#417]
Hi,

not sure I already asked this. Is there a reason you chose "Orphanet:524" vs. the (IMHO correct) "ORPHA:524" ?

Thanks for any replies.

**Comment by pnrobinson** [comment]
I agree we should use ORPHA
A related comment is that I think the correct prefix should be MIM and not OMIM

**Comment by drseb** [comment]
To my knowledge only one is correct (ORPHA:XXX). I spoke with Annie about this

**Comment by mellybelly** [comment]
ok lets fix in the file then, but we should still support the alt prefix in Prefix commons

**Comment by cmungall** [comment]
In the official OWL releases created by Orphanet the prefix is `Orphanet`, see for example:

https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_790

note however the ontology id registered with OLS is `ordo` (in OBO the ontology id and prefix must be identical but ordo is not registered via OBO).

MONDO will have to keep using the `Orphanet` prefix until the official OWL ontology changes. I'll close this until then.

cc @annieolry @SimonJupp
