### ISSUE TITLE
Some disease description text has strange references embedded

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-disease-ontology#422]
https://github.com/monarch-initiative/monarch-app/issues/1535

Have a look at the description here https://monarchinitiative.org/MONDO:0007947.

"At least 25% of cases are due to a new ( de novo ) mutation.[76][10605] Treatment is based on the signs and symptoms in each person.[10605]"

I don't know what these numbers are meant to be, but it is cruft that should be omitted.

Chris writes 

"Not sure if we have resources to rewrite the gard scraper but if not I'll hack in some perl to strip these"

**Comment by cmungall** [comment]
Fixed here: https://github.com/monarch-initiative/mondo-build/commit/c2abf6629bffa5a1b6e4a6dea8eb17a4b4526f53

(tagged wrong repo)
