### ISSUE TITLE
EFO diseases

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-disease-ontology#57]
it seems EFO has disease identifiers, like [eye diseases](http://www.ebi.ac.uk/efo/EFO_0003966).  we need to be able to bridge these, so we can use the gwas data they've curated.

**Comment by mellybelly** [comment]
yet another disease ontology!

On Oct 28, 2015, at 5:39 PM, Nicole Washington <notifications@github.com<mailto:notifications@github.com>> wrote:


it seems EFO has disease identifiers, like eye diseases<http://www.ebi.ac.uk/efo/EFO_0003966>. we need to be able to bridge these, so we can use the gwas data they've curated.

—
Reply to this email directly or view it on GitHub<https://github.com/monarch-initiative/monarch-disease-ontology/issues/57>.

Dr. Melissa Haendel

Associate Professor
Ontology Development Group, OHSU Library
www.ohsu.edu/library/ontology<http://www.ohsu.edu/library/ontology>
Department of Medical Informatics and Clinical Epidemiology
Oregon Health & Science University
haendel@ohsu.edu<mailto:haendel@ohsu.edu>
skype: melissa.haendel
503-407-5970

**Comment by pnrobinson** [comment]
Hi everybody,
I know Helen pretty well and I think the EFO has disease terms out of necessity, i.e., there is/was no other option that would make the EBI resources do what they should do. We should try to synergise with respect to diseases in the future!
-Peter

Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Professor of Bioinformatics, Freie Universität Berlin
Institut für Medizinische Genetik und Humangenetik
Charité - Universitätsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de
http://compbio.charite.de
http://www.human-phenotype-ontology.org
I have learned from my mistakes, and I am sure I can repeat them exactly
ORCID ID:http://orcid.org/0000-0002-0736-9199
Scopus Author ID 7403719646
Appointment request: http://doodle.com/pnrobinson
________________________________
Von: Melissa Haendel [notifications@github.com]
Gesendet: Donnerstag, 29. Oktober 2015 01:56
An: monarch-initiative/monarch-disease-ontology
Betreff: Re: [monarch-disease-ontology] EFO diseases (#57)

yet another disease ontology!

On Oct 28, 2015, at 5:39 PM, Nicole Washington <notifications@github.com<mailto:notifications@github.com>> wrote:


it seems EFO has disease identifiers, like eye diseases<http://www.ebi.ac.uk/efo/EFO_0003966>. we need to be able to bridge these, so we can use the gwas data they've curated.

—
Reply to this email directly or view it on GitHub<https://github.com/monarch-initiative/monarch-disease-ontology/issues/57>.

Dr. Melissa Haendel

Associate Professor
Ontology Development Group, OHSU Library
www.ohsu.edu/library/ontology<http://www.ohsu.edu/library/ontology>
Department of Medical Informatics and Clinical Epidemiology
Oregon Health & Science University
haendel@ohsu.edu<mailto:haendel@ohsu.edu>
skype: melissa.haendel
503-407-5970

**Comment by mellybelly** [comment]
Oh its no worry, we work well with EFO:-)

On Oct 28, 2015, at 11:12 PM, Peter Robinson <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi everybody,
I know Helen pretty well and I think the EFO has disease terms out of necessity, i.e., there is/was no other option that would make the EBI resources do what they should do. We should try to synergise with respect to diseases in the future!
-Peter

Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Professor of Bioinformatics, Freie Universität Berlin
Institut für Medizinische Genetik und Humangenetik
Charité - Universitätsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de<mailto:peter.robinson@charite.de>
http://compbio.charite.de
http://www.human-phenotype-ontology.org
I have learned from my mistakes, and I am sure I can repeat them exactly
ORCID ID:http://orcid.org/0000-0002-0736-9199<http://orcid.org/0000-0002-0736-9199>
Scopus Author ID 7403719646
Appointment request: http://doodle.com/pnrobinson
________________________________
Von: Melissa Haendel [notifications@github.com<mailto:notifications@github.com>]
Gesendet: Donnerstag, 29. Oktober 2015 01:56
An: monarch-initiative/monarch-disease-ontology
Betreff: Re: [monarch-disease-ontology] EFO diseases (#57)

yet another disease ontology!

On Oct 28, 2015, at 5:39 PM, Nicole Washington <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


it seems EFO has disease identifiers, like eye diseases<http://www.ebi.ac.uk/efo/EFO_0003966>. we need to be able to bridge these, so we can use the gwas data they've curated.

—
Reply to this email directly or view it on GitHub<https://github.com/monarch-initiative/monarch-disease-ontology/issues/57>.

Dr. Melissa Haendel

Associate Professor
Ontology Development Group, OHSU Library
www.ohsu.edu/library/ontology<http://www.ohsu.edu/library/ontology><http://www.ohsu.edu/library/ontology>
Department of Medical Informatics and Clinical Epidemiology
Oregon Health & Science University
haendel@ohsu.edu<mailto:haendel@ohsu.edu><mailto:haendel@ohsu.edu>
skype: melissa.haendel
503-407-5970


—
Reply to this email directly or view it on GitHub<https://github.com/monarch-initiative/monarch-disease-ontology/issues/57#issuecomment-152043504>.

—
Reply to this email directly or view it on GitHub<https://github.com/monarch-initiative/monarch-disease-ontology/issues/57#issuecomment-152089432>.

Dr. Melissa Haendel

Associate Professor
Ontology Development Group, OHSU Library
www.ohsu.edu/library/ontology<http://www.ohsu.edu/library/ontology>
Department of Medical Informatics and Clinical Epidemiology
Oregon Health & Science University
haendel@ohsu.edu<mailto:haendel@ohsu.edu>
skype: melissa.haendel
503-407-5970

**Comment by cmungall** [comment]
EFO now fully integrated into MONDO
