### ISSUE TITLE
Duplicate of MESH terms: 

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology#81]
MESH_C536046 Osteogenesis, imperfecta, type 5
MESH_C567042 Osteogenesis Imperfecta, Type V

These terms are duplicates and MonDO is trying to make them subclasses but there is a low probability scores.

![image](https://cloud.githubusercontent.com/assets/6722114/15343622/21eeae62-1c53-11e6-966b-438075931019.png)

**Comment by nicolevasilevsky** [comment]
The same issue exists with Type 6 terms:
MESH_C536047 Osteogenesis imperfecta, type 6
MESH_C567041 Osteogenesis Imperfecta, Type VI

![image](https://cloud.githubusercontent.com/assets/6722114/15343685/d66a402c-1c53-11e6-975c-bd818d5ec955.png)

**Comment by nicolevasilevsky** [comment]
And Type 7:
MESH_C536048 Osteogenesis imperfecta, type 7
MESH_C565200 Osteogenesis Imperfecta, Type VII

![image](https://cloud.githubusercontent.com/assets/6722114/15343721/3102bcbc-1c54-11e6-919b-b5a6d7b6e582.png)

**Comment by nicolevasilevsky** [comment]
TO DO: Check MeSH's website

**Comment by nicolevasilevsky** [comment]
0.09259259259259259     MESH_C565840 Long Qt Syndrome 3 SubClassOf OMIM_603830 Long Qt Syndrome 3

**Comment by nicolevasilevsky** [comment]
0.09615384615384616     MESH_C537978 Camurati Engelmann disease, type 2 SubClassOf OMIM_606631 Camurati-Engelmann Disease, Type 2

**Comment by TomMetz** [comment]
Any way for me to be removed from this list?



On May 17, 2016, at 6:01 PM, nicolevasilevsky <notifications@github.com<mailto:notifications@github.com>> wrote:


0.09615384615384616 MESH_C537978 Camurati Engelmann disease, type 2 SubClassOf OMIM_606631 Camurati-Engelmann Disease, Type 2

**Comment by balhoff** [comment]
@TomMetz I think probably what you want is to unwatch the repository: https://github.com/monarch-initiative/monarch-disease-ontology/watchers

**Comment by nicolevasilevsky** [comment]
@cmungall I think these should just be made equivalent. What do you think? I'll do so tomorrow if I don't hear back from you.

**Comment by nicolevasilevsky** [comment]
These should be fixed upstream according to @cmungall. Reassigning.

**Comment by nicolevasilevsky** [comment]
here is another example of duplicate terms in MeSH:
0.09259259259259259     MESH_C565840 Long Qt Syndrome 3 SubClassOf OMIM_603830 Long Qt Syndrome 3

**Comment by nicolevasilevsky** [comment]
Another duplicate in MeSH:
0.09615384615384616     MESH_C537978 Camurati Engelmann disease, type 2 SubClassOf OMIM_606631 Camurati-Engelmann Disease, Type 2

**Comment by cmungall** [comment]
wait, those last 2 aren't MESH dupes

**Comment by nicolevasilevsky** [comment]
I updated the comments above

**Comment by cmungall** [comment]
I'm curating two sets:

 1. curated-duplicates.tsv - we believe to be duplicates
 2. curated-distinct.tsv - ones that look deceptively like they should be merged but are genuinely distinct

An example of the latter:

```
[Term]
id: MESH:C538664
name: PICA syndrome
is_a: MESH:D014854 ! Lateral Medullary Syndrome
synonym: "Vertebral artery syndrome" EXACT []


[Term]
id: MESH:D010842
name: Pica
def: "The persistent eating of nonnutritive substances for a period of at least one month. (DSM-IV)" [MESH:D010842]
is_a: MESH:D001068 ! Feeding and Eating Disorders
synonym: "Allotriophagy" EXACT []
synonym: "Geophagia" EXACT []
```

**Comment by cmungall** [comment]
Added

```
$ grep Camurati curated-duplicates.tsv 
MESH:C537978    Camurati Engelmann disease, type 2      MESH:C564689    Camurati-Engelmann Disease, Type II     unrelated
```
