### ISSUE TITLE
Review classification of Renal cell carcinoma in MonDO

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-disease-ontology#95]
http://purl.obolibrary.org/obo/DOID_4464

**Comment by nicolevasilevsky** [comment]
![image](https://cloud.githubusercontent.com/assets/6722114/15757847/7283fd94-28bc-11e6-922f-4853edb56b13.png)

**Comment by nicolevasilevsky** [comment]
I don't think renal mellulary carcinoma is equiv to collecting duct carcinoma, as the collecting duct system of the kidney consists tubules and ducts (https://en.wikipedia.org/wiki/Collecting_duct_system). There is the renal medulla collecting duct, but I am uncertain if the 'renal medullary carcinoma' in this case is the same. 

![image](https://cloud.githubusercontent.com/assets/6722114/15760099/8d101814-28c6-11e6-8f9d-0551da1bc2e9.png)

**Comment by nicolevasilevsky** [comment]
I think Orphanet_319276 and DOID_4467 are equiv based on the labels. 

![image](https://cloud.githubusercontent.com/assets/6722114/15760311/73457c5c-28c7-11e6-865a-1f863f4e9b96.png)

**Comment by nicolevasilevsky** [comment]
![image](https://cloud.githubusercontent.com/assets/6722114/15760397/da70ed80-28c7-11e6-9fc4-18c7458958fe.png)

**Comment by nicolevasilevsky** [comment]
I think DOID_4468 is a subclass of Orphanet_319276 because adenocarcinoma is a subclass of carcinoma in other parts of the ontology. For example: 
![image](https://cloud.githubusercontent.com/assets/6722114/15760630/d72668de-28c8-11e6-830e-aaa45370d96f.png)


![image](https://cloud.githubusercontent.com/assets/6722114/15760578/b6859b5e-28c8-11e6-91a3-f605e1d1c073.png)

**Comment by nicolevasilevsky** [comment]
I think these are equiv because mesonephroma is a synonym of the DOID term.

![image](https://cloud.githubusercontent.com/assets/6722114/15760704/411514fc-28c9-11e6-9133-5492a3bc78c5.png)

**Comment by nicolevasilevsky** [comment]
I think all these should be equiv based on the labels, in agreement with KBOOM.

![image](https://cloud.githubusercontent.com/assets/6722114/15760831/f7bab36a-28c9-11e6-9a91-f9f94b295214.png)

**Comment by nicolevasilevsky** [comment]
[Issue95.pptx](https://github.com/monarch-initiative/monarch-disease-ontology/files/296662/Issue95.pptx)

**Comment by nicolevasilevsky** [comment]
[Issue95.pptx](https://github.com/monarch-initiative/monarch-disease-ontology/files/296663/Issue95.pptx)

**Comment by cmungall** [comment]
> I don't think renal mellulary carcinoma is equiv to collecting duct carcinoma

good catch. Can you determine why kboom places a strong prior weighting on this hypothesis? Hint: if you open set-1.owl in Protege, you should see the collected set of classes, unmerged. You can examine synonyms here.

In this case:

```
id: DOID:4464
name: collecting duct carcinoma
synonym: "renal Medullary carcinoma" EXACT [NCI2004_11_17:C7572]
...
```

If you disbelieve the equivalence, you can do two things

 1. Override the prior by placing a 0 or near zero probability on his hypothesis in curated-ptable.tsv 
 2. File a request on the DO tracker requesting that they either remove the syn, or weaken it from EXACT

Obviously 1 will be faster and will take effect next round.

**Comment by cmungall** [comment]
> mesonephroma

I don't know anything about this one - do you think this is a mistake in DO or do you believe it?

**Comment by cmungall** [comment]
> I think DOID_4468 is a subclass of Orphanet_319276 because adenocarcinoma is a subclass of carcinoma in other parts of the ontology

It's not that sophisticated! 

I think this is ultimately due to synonyms in DO:

```
id: DOID:4468
name: clear cell adenocarcinoma
namespace: disease_ontology
alt_id: DOID:2617
alt_id: DOID:4940
def: "An adenocarcinoma that derives_from epithelial cells which have clear cytoplasm." [url:http://www.pathconsultddx.com/pathCon/diagnosis?pii=S1559-8675%2806%2970166-8]
synonym: "Clear cell adenocarcinoma (morphologic abnormality)" EXACT [SNOMEDCT_2005_07_31:30546008]
synonym: "Clear cell adenocarcinoma NOS (morphologic abnormality)" EXACT [SNOMEDCT_2005_07_31:189633003]
synonym: "Mesonephroid Clear cell carcinoma" EXACT [NCI2004_11_17:C3766]
synonym: "Mesonephroma NOS (morphologic abnormality)" EXACT [SNOMEDCT_2005_07_31:189861007]
synonym: "Mesonephroma, malignant (morphologic abnormality)" EXACT [SNOMEDCT_2005_07_31:2221008]
synonym: "Water-Clear cell adenocarcinoma" EXACT [NCI2004_11_17:C4156]
synonym: "Water-clear cell adenocarcinoma (morphologic abnormality)" EXACT [SNOMEDCT_2005_07_31:80727009]
synonym: "Water-clear cell carcinoma" EXACT []
synonym: "Wolffian duct neoplasm" EXACT [NCI2004_11_17:C6782]
synonym: "malignant Mesonephroma" EXACT [NCI2004_11_17:C4072]
synonym: "mesonephroma" EXACT []
xref: MESH:D008649
xref: MESH:D018262
xref: NCIT:C36815
xref: NCIT:C3766
xref: NCIT:C4072
xref: NCIT:C4156
xref: SCTID:189633003
xref: SCTID:189861007
xref: SCTID:2221008
xref: SCTID:30546008
xref: SCTID:80727009
xref: UMLS:C0025490
xref: UMLS:C0206681
xref: UMLS:C0334322
is_a: DOID:299  ! adenocarcinoma
```

I think I'm fairly confident in saying DO is wrong here. CCCs seem to appear in multiple places, not just the kidneys and their precursors: https://en.wikipedia.org/wiki/Clear-cell_adenocarcinoma.

I guess you could say it's ok to keep these syns and demote them to NARROW, that would improve the estimation of the priors. But really, I don't think subclasses should be added as synoyms. To the DO tracker! And in the interim, override the prior (either 0 the prob of equivalence, or if you are confident of the inter-ontology subclass, do a 1 on that!)

**Comment by pnrobinson** [comment]
Clear-cell adenocarcinoma is a type of adenocarcinoma that shows clear cells. (That is there are multiple types of clear-cell adenocarcinoma). mesonephroma is an Obsolete term for a relatively rare malignant neoplasm of the ovary and corpus uteri, One of the many synoynms I found for this is "Clear-cell adenocarcinoma", but if the synonym is correct it is a VERY_BROAD_SYNYONYM. Therefore, the "EXACT" in "synonym: "mesonephroma" EXACT []" is erroneous.

**Comment by cmungall** [comment]
Thanks Peter! I have anecdotally noticed many of these problematic EXACT synonyms. I suspect they derive from an early attempt to build the DO from multiple sources. We downweight the importance of the synonym compared to the label when assigning priors, but the algorithm can still get stumped by peculiar combinations of problematic xrefs

**Comment by nicolevasilevsky** [comment]
@pnrobinson and @cmungall 
so it sounds like for this case, mesonephroma and malignant mesoneprhoma should not be synonyms of 'clear cell adenocarcinoma, and I should submit a ticket with DO to remove these?

@cmungall I should add:
0.0 MESH_D008649 Mesonephroma EquivalentTo DOID_4468 clear cell adenocarcinoma
to curated-ptable.tsv file, yes?

thank you!

![image](https://cloud.githubusercontent.com/assets/6722114/15831864/814dc5a6-2bd4-11e6-8ecc-d3938dbd398e.png)

**Comment by nicolevasilevsky** [comment]
added ticket to DO tracker re: clear cell adenocarcinoma
https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/150

**Comment by cmungall** [comment]
On 6 Jun 2016, at 10:53, nicolevasilevsky wrote:

> @pnrobinson and @cmungall
> so it sounds like for this case, mesonephroma and malignant 
> mesoneprhoma should not be synonyms of 'clear cell adenocarcinoma, and 
> I should submit a ticket with DO to remove these?

Yes

>
> @cmungall I should add:
> 0.0 MESH_D008649 Mesonephroma EquivalentTo DOID_4468 clear cell 
> adenocarcinoma
> to curated-ptable.tsv file, yes?

Yes, that we can override immediately without waiting for DO

**Comment by nicolevasilevsky** [comment]
added  0.0 MESH_D008649 Mesonephroma EquivalentTo DOID_4468 clear cell
 adenocarcinoma to the curated-ptable.tsv file

**Comment by nicolevasilevsky** [comment]
I think all the issues with this have been addressed and the ticket can be closed? @cmungall
