### ISSUE TITLE
Detect ORDO obsoletions

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-disease-ontology#96]
See
https://github.com/monarch-initiative/monarch-app/issues/1254#issuecomment-224721529

ORDO does not use owl:deprecated

It makes things a subclass of a special obsolete class class:

```
   <owl:Class rdf:about="http://www.orpha.net/ORDO/Orphanet_93564">
        <rdfs:subClassOf rdf:resource="http://www.orpha.net/ORDO/ObsoleteClass"/>
        <efo:reason_for_obsolescence rdf:datatype="&xsd;string">use http://www.orpha.net/ORDO/Orphanet_767 with label: Polyarteritis nodosa</efo:reason_for_obsolescence>
        <rdfs:label rdf:datatype="&xsd;string">Pediatric polyarteritis nodosa</rdfs:label>
    </owl:Class>
    
```

We should map this to owl:deprecated

We could also try and parse out the replaced-by link

What is odd is that it doesn't show up on the main orphanet site, but I guess we take ORDO as canonical here

**Comment by jmcmurry** [comment]
+1

**Comment by cmungall** [comment]
This fix obsoletes 499 ORDO classes. Will be reflected in next mondo build
